--UN CLIENTE COMPRA UN VEHICULO
CREATE DATABASE COMPRAVEHICULO;

USE COMPRAVEHICULO;

CREATE TABLE CLIENTE(
CI         VARCHAR(30) PRIMARY KEY,
NOM_CLIENT VARCHAR(30),
GMAIL      VARCHAR(25),
TELEFONO   INTEGER
);

INSERT INTO CLIENTE(CI,NOM_CLIENT,GMAIL,TELEFONO)
VALUES      ('12657434','JHONNY TORRES','JHONNY@GMAIL.COM',65557545);

SELECT * FROM CLIENTE;

CREATE TABLE EMPRESA(
COD_PROD     VARCHAR(30) PRIMARY KEY,
NOM_EMPRESA  VARCHAR(30),
NOM_EMP      VARCHAR(30),
PRODUCTO     VARCHAR(30),
UBICACION    VARCHAR(30),
NUM_EMPRESA  INTEGER
);
INSERT INTO EMPRESA(COD_PROD,NOM_EMPRESA,PRODUCTO,UBICACION,NUM_EMPRESA)
VALUES     ('TYT-13245','IMCRUZ','MINIVAN','C/SAVEDRA/AV/SAN PABLO',2322425);

CREATE TABLE COMPRA(
COD_PRODUCTO   VARCHAR(30) PRIMARY KEY,
PRODUCTO       VARCHAR(30),
NOM_PROD       VARCHAR(30),
GARANTIA       VARCHAR(30),
PRECIO         INTEGER,
GESTION        INTEGER
);

INSERT INTO COMPRA(COD_PRODUCTO,PRODUCTO,NOM_PROD,GARANTIA,PRECIO,GESTION)
VALUES      ('TYT-13245','MINIVAN','TOYOTA ODYSSEY','2 AÑOS',12.000,2022);

SELECT * FROM COMPRA;
CREATE TABLE FACTURA(
NOM_CLIENT  VARCHAR(30),--CLIENTE
CI          VARCHAR(30) PRIMARY KEY,--CLIENTE
PRECIO      INTEGER,    --COMPRA
NOM_PROD    VARCHAR(30),--CONPRA
GARANTIA    VARCHAR(30),--CONPRA
NOM_EMPRESA VARCHAR(30),--EMPRESA
COD_PRODUCTO   VARCHAR(30) 
--solo rpiamry key
FOREIGN KEY (CI) REFERENCES CLIENTE(CI),
FOREIGN KEY (COD_PRODUCTO) REFERENCES COMPRA(COD_PRODUCTO),
--FOREIGN KEY (NOM_CLIENT) REFERENCES COMPRA(NOM_CLIENT),
--FOREIGN KEY (NOM_CLIENT) REFERENCES EMPRESA(NOM_CLIENT),
);

INSERT INTO FACTURA(NOM_CLIENT,CI,PRECIO,NOM_PROD,GARANTIA,NOM_EMPRESA,COD_PRODUCTO)
VALUES ('JHONNY TORRES','12657434',12.000,'TOYOTA ODYSSEY','2 AÑOS','IMCRUZ','TYT-13245');
SELECT * FROM FACTURA;